#389. Find the Difference
#Easy
#
#You are given two strings s and t.
#
#String t is generated by random shuffling string s and then add one more
#letter at a random position.
#
#Return the letter that was added to t.
#
#Example 1:
#Input: s = "abcd", t = "abcde"
#Output: "e"
#Explanation: 'e' is the letter that was added.
#
#Example 2:
#Input: s = "", t = "y"
#Output: "y"
#
#Constraints:
#    0 <= s.length <= 1000
#    t.length == s.length + 1
#    s and t consist of lowercase English letters.

from collections import Counter

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        """XOR approach - all characters cancel except the added one"""
        result = 0
        for c in s + t:
            result ^= ord(c)
        return chr(result)


class SolutionCounter:
    """Using Counter"""

    def findTheDifference(self, s: str, t: str) -> str:
        count_s = Counter(s)
        count_t = Counter(t)

        for char in count_t:
            if count_t[char] != count_s[char]:
                return char


class SolutionSum:
    """Using sum of ASCII values"""

    def findTheDifference(self, s: str, t: str) -> str:
        return chr(sum(ord(c) for c in t) - sum(ord(c) for c in s))


class SolutionArray:
    """Using count array"""

    def findTheDifference(self, s: str, t: str) -> str:
        count = [0] * 26

        for c in s:
            count[ord(c) - ord('a')] += 1
        for c in t:
            count[ord(c) - ord('a')] -= 1

        for i in range(26):
            if count[i] == -1:
                return chr(i + ord('a'))
